ARG DEPENDENCY_IMAGE
FROM ${DEPENDENCY_IMAGE}

WORKDIR /work
COPY learning/ ./learning/
COPY code-manifest.json ./code-manifest.json
RUN python -c "from learning.smolvla.prepare import _source_license; from learning.smolvla.cloud_assets import validate_vendor_inventory; from learning.smolvla.checkpoint_runner import native_runtime; _source_license(); native_runtime()"
